### ISSUE TITLE
queue.Empty error in queye.py

### ISSUE THREAD

**Issue by lessless** [SublimeLinter/SublimeLinter-rubocop#28]
Hello, all of a sudden rubocop linter stopped to work with following error
```python
SublimeLinter: -------------------- 
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/lessless/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lessless/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/lessless/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/lessless/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/lessless/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 924, in lint_view
    linter.lint(hit_time)
  File "/Users/lessless/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1367, in lint
    cmd = self.get_cmd()
  File "/Users/lessless/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1119, in get_cmd
    return self.build_cmd()
  File "/Users/lessless/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1169, in build_cmd
    cmd[0:1] = util.convert_type(path, [])
  File "./posixpath.py", line 379, in abspath
  File "./posixpath.py", line 64, in isabs
AttributeError: 'list' object has no attribute 'startswith'
 
SublimeLinter: -------------------- 
```

Sublime: build 3083
Python:  v. 2.7.10

**Comment by joshmfrankel** [comment]
Sounds like a similiar issue was experienced [here as well](https://github.com/SublimeLinter/SublimeLinter-jshint/issues/57). The same queue.Empty error.

I would give this a shot, if you are still encountering the above error. :-)

> Reinstalling SublimeLinter helps me
> -st4lk

**Comment by joshmfrankel** [comment]
I actually ran into this after installing another linter. From looking at your error report this line in particular seems relevant:

> AttributeError: 'list' object has no attribute 'startswith'

**Comment by joshmfrankel** [comment]
@lessless Are you still experiencing this issue? :-)

**Comment by lessless** [comment]
nope :)

**Comment by joshmfrankel** [comment]
@lessless Just for curiosities sake (and before I close the issue), any idea what fixed the issue? Ruby version update? Rubocop updated? Something else?

**Comment by lessless** [comment]
Sorry, can't remember the exact reason, but I believe it was update.

**Comment by jacobdr** [comment]
Uninstalling and then reinstalling sublimelinter via package control solved the issue for me

**Comment by flintforge** [comment]
The error was related to the project settings for me :
```
"SublimeLinter":
	{
-		"@python": 3.4,
```

```
"SublimeLinter":
	{
+		"@python": "3.4",
```
