### ISSUE TITLE
No finding correct Rubocop version

### ISSUE THREAD

**Issue by quintrino** [SublimeLinter/SublimeLinter-rubocop#45]
Hi, 

I'm trying to understand the error that I'm receiving. 

I've had both the SL Rubocop version and the standalone Rubocop plugin installed. I've disabled the stand alone Rubocop Plugin as I prefer the Sublime Linter Rubocop version. 

the standalone Rubocop plugin works when I run it manually, but I haven't been able to get Sublime Linter Rubocop working automatically. I'll be happy for any help that points me in the right direction. 

I suspect the issue might be PATH related but I've tried using the 
$Which Rubocop
and adding that to the settings like so:

        "paths": {
            "linux": [],
            "osx": [
                "/usr/local/bin"
            ],
            "windows": []
        }

I've also tried paths such as:
/Users/prime/.rvm/gems/ruby-2.4.1/bin/
/Users/prime/.rvm/gems/ruby-2.3.0/bin/

I've tried uninstalling both Sublime Linter and SL Rubocop neither of which seems to have worked. 

Here is the full log that I get when opening Sublime and try to have SL Rubocop lint a file. 

```
startup, version: 3143 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/prime/Library/Application Support/Sublime Text 3/Packages
state path: /Users/prime/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/prime/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["RuboCop", "Vintage"]
pre session restore time: 0.266923
using gpu buffer for window
loading dictionary Packages/Language - English/en_US.dic
startup time: 0.392131
using gpu buffer for window
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin Alignment.Alignment
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Colorsublime.colorsublime-plugin
reloading plugin GitGutter.plugin
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin RawLineEdit.raw_line_edit
reloading plugin SublimeLinter-rubocop.linter
SublimeLinter: rubocop linter loaded 
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/xj/qfqm8tf971gbw3vvcvslsgwc0000gn/T/SublimeLinter3-prime 
SublimeLinter: user shell: /bin/zsh 
SublimeLinter: computed PATH using /bin/zsh:
/usr/local/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Users/prime/.rvm/gems/ruby-2.4.1/bin
/Users/prime/.rvm/gems/ruby-2.4.1@global/bin
/Users/prime/.rvm/rubies/ruby-2.4.1/bin
/Users/prime/.rvm/bin
/usr/local/opt/python/libexec/bin
 
SublimeLinter: ENV['GEM_HOME'] = '/Users/prime/.rvm/gems/ruby-2.4.1' 
Package Control: Skipping automatic upgrade, last run at 2017-10-23 11:15:07, next run at 2017-10-23 12:15:07 or after
SublimeLinter: rubocop version query: /Users/prime/.rvm/bin/rvm-auto-ruby -S rubocop --version 
SublimeLinter: rubocop version: 0.51.0 
SublimeLinter: rubocop: (>= 0.34.0) satisfied by 0.51.0 
SublimeLinter: rubocop activated: ['/Users/prime/.rvm/bin/rvm-auto-ruby'] 
SublimeLinter: rubocop: advert_controller.rb ['ruby', '-S', 'rubocop', '--format', 'emacs', '--force-exclusion', '--stdin', '/Users/prime/Code/folder/app/controllers/advert_controller.rb'] 
SublimeLinter: rubocop output:
Ignoring bcrypt-3.1.11 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.11
Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
Ignoring bindex-0.5.0 because its extensions are not built.  Try: gem pristine bindex --version 0.5.0
Ignoring byebug-9.1.0 because its extensions are not built.  Try: gem pristine byebug --version 9.1.0
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18
Ignoring gem-wrappers-1.4.0 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.4.0
Ignoring gem-wrappers-1.3.2 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.3.2
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring nio4r-2.1.0 because its extensions are not built.  Try: gem pristine nio4r --version 2.1.0
Ignoring nokogiri-1.8.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.8.1
Ignoring oj-3.3.8 because its extensions are not built.  Try: gem pristine oj --version 3.3.8
Ignoring oj-2.18.5 because its extensions are not built.  Try: gem pristine oj --version 2.18.5
Ignoring openssl-2.0.6 because its extensions are not built.  Try: gem pristine openssl --version 2.0.6
Ignoring pg-0.21.0 because its extensions are not built.  Try: gem pristine pg --version 0.21.0
Ignoring psych-2.2.4 because its extensions are not built.  Try: gem pristine psych --version 2.2.4
Ignoring puma-3.10.0 because its extensions are not built.  Try: gem pristine puma --version 3.10.0
Ignoring rainbow-2.2.2 because its extensions are not built.  Try: gem pristine rainbow --version 2.2.2
Ignoring unf_ext-0.0.7.4 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.4
Ignoring websocket-driver-0.7.0 because its extensions are not built.  Try: gem pristine websocket-driver --version 0.7.0
Ignoring websocket-driver-0.6.5 because its extensions are not built.  Try: gem pristine websocket-driver --version 0.6.5
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rainbow (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/prime/.rvm/gems/ruby-2.4.1/gems/rubocop-0.51.0/lib/rubocop.rb:4:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/prime/.rvm/gems/ruby-2.4.1/gems/rubocop-0.51.0/bin/rubocop:6:in `<top (required)>'
	from /usr/local/bin/rubocop:22:in `load'
	from /usr/local/bin/rubocop:22:in `<main>' 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fbda4482ac0> 
environment variables loaded using: /bin/zsh -l

```

Any help is greatly appreciated.

**Comment by quintrino** [comment]
In the end the way that finally worked for me in resolving this was to implode rvm and switch to rbenv.
